services:
    database:
        image: postgres
        container_name: database
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: example
    php:
        container_name: php
        build:
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/backend/
        ports:
            - 9000:9000
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
